server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: localhost
  port: 5432
  name: payment_system
  user: postgres
  password: postgres123
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

kafka:
  brokers:
    - localhost:9092
  topic: payment-events
  consumer_group: payment-service
  batch_size: 100
  batch_timeout: 10ms

gateway:
  provider: stripe
  base_url: https://api.stripe.com
  api_key: sk_test_your_stripe_key_here
  timeout: 30s
  max_retries: 3
  circuit_breaker:
    max_failures: 5
    reset_timeout: 60s

metrics:
  enabled: true
  port: 9091
  path: /metrics
  alert_check_interval: 30s

logging:
  level: info
  format: json
  output_path: stdout

environment: development
